name: Docker Build

inputs:
  context:
    required: true
    type: string
  dockerfile:
    required: true
    type: string
  image_tag:
    required: true
    type: string
  environment:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Build Docker image
      shell: bash
      run: |
        
        docker build \
          --build-arg NODE_ENV=${{ inputs.environment }} \
          -t ${{ inputs.image_tag }} \
          -f ${{ inputs.dockerfile }} \
          ${{ inputs.context }}
