name: Docker Push to ECR

inputs:
  image_tag:
    required: true
    type: string
  ecr_repository:
    required: true
    type: string
secrets:
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true

env:
  AWS_REGION: us-east-1


runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Tag and push image to ECR
      shell: bash
      run: |
        docker tag ${{ inputs.image_tag }} ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}:${{ inputs.image_tag }}
        docker push ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}:${{ inputs.image_tag }}
