name: AWS Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: c2e
  TERRAFORM_VERSION: 1.10.5
  TERRAGRUNT_VERSION: 0.73.6

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    
    - name: Install Terragrunt
      run: |
        wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Terragrunt Plan
      run: |
        cd infrastructure
        terragrunt run-all plan --terragrunt-working-dir ${{ inputs.environment }}
    
    - name: Terragrunt Apply
      run: |
        cd infrastructure
        terragrunt run-all apply -auto-approve --terragrunt-working-dir ${{ inputs.environment }}
