name: Docker Build

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      build_args:
        required: false
        type: string
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker image
      run: |
        BUILD_ARGS=""
        if [ ! -z "${{ inputs.build_args }}" ]; then
          while IFS= read -r line; do
            BUILD_ARGS="$BUILD_ARGS --build-arg $line"
          done <<< "${{ inputs.build_args }}"
        fi
        
        docker build \
          $BUILD_ARGS \
          -t ${{ inputs.image_tag }} \
          -f ${{ inputs.dockerfile }} \
          ${{ inputs.context }}
